
# Git

C:/Users/memy/OneDrive/Pulpit/1_Programs_and_programing/GIT/git_test/repo1



## Uwagi rozne

Wystarczy podawać PIERWSZE 8 znakow numeru commit-u.

Moze wystapic problem kiedy w pliku zostana zrobione zmiany w dwoch roznych programach (np. w samym Git i w Git pod Rstudio). Wtedy trzeba usunac odpowiedni plik poleceniem w konsoli Git.

## roznice/zmiany

### zmiany jakie sa w stage wzgledem tego to jest przed poczekalnia
```
git diff
```
### zmiany jakie sa w stage wzgledem poprzedniego commitu
```
git diff --staged
```
### roznice miedzy branchami
```
git diff branch_1 branch_2  
```
### zmiany w konkretnym commicie
```
git show hash_7
```
### roznice miedzy dwoma zadanymi commitami
```
git diff hash_7_1 hash_7_2
```
### roznica miedzy zadanym commitem i commitem na ktorym jest wskaznik
```
git diff hash_7 HEAD
```



## stages

### cofniecie pliku z stage (poczekalni)
```
git reset HEAD nazwa_pliki   
```

### dodanie do stage wszystkich modyfikacji
```
git add .
```
### dodanie do stage modyfikacji w konkretnym pliku
```
git add naza_pliku
```



## repozytoria

### lista repozytoriow zdalnych
```
git remote -v
```

### dodanie polaczenia do zdalnego repo
```
git remote add origin  git@github.com:USERNAME/REPOSITORY.git
```
### zmiana url dla istniejącego polaczenia
```
git remote set-url origin git@github.com:USERNAME/REPOSITORY.git
```

### usuniecie poloczenia do zdalnego repo ktore przy laczeniu nazwalismy 'origin'
```
git remote rm origin
```






## branches

### lista lokalnych branchow
```
git branch
```

### lista wszyskich branchow ( branche zdalne są na czerwowo)
```
git branch --all
```

### przelaczenie sie na inny branch
```
git checkout <branch>
```
### utworzenie nowego brancha i przelaczenie sie na niego
```
git checkout -b <branch>
```
### utworzenie nowego brancha bez przelaczenie sie na niego
```
git branch <name_of_your_new_branch>
```
### usuniecie brancha
```
git branch -d branch_name
git branch -D branch_name
```
The -d option stands for --delete, which would delete the local branch, only if you have already pushed and merged it with your remote branches.
The -D option stands for --delete --force, which deletes the branch regardless of its push and merge status, so be careful using this one!

### usuniecie zdalnego brancha
```
git push <remote_name> --delete <branch_name>
```
### utworzenia zdalnego brancha:
Najpierw tworzymy go lokalnie. A potem pushujemy odpowiednio. 

```
Syntax:
$ git push <REMOTE_NAME> <LOCAL_BRANCH_NAME>:<REMOTE_BRANCH_NAME>

Command:
$ git push origin stage1:development
```
Przykla ze strony:
[How to Create a Branch in Remote Git Repository](https://tecadmin.net/how-to-create-a-branch-in-remote-git-repository/)





## commits


### commit dla konkretnego pliku
```
git commit nazwa_pliku -m '.'
```
### add i commit w jednej komendzie
```
git commit -am "comment"
```
### lista commits
```
git log 
```

### lista commitow dla konkretnego pliku
```
git log nazwa_pliku
```

### lista commitow dla konkretnego brancha (tutaj 'master')
```
git log master
```

### modyfikacja do komentarza w ostatniej zmianie
```
git commit --amend
```
W chodzę w VIM w tryb umozliwiajacy zmiany i poprawiam pierwsze linijke gdzie jest komentarz. Naciskam <esc> i potem :wq i <enter> 




## commits -wskazniki


### przesuniecie wskaznika na zadany commit na branchu 'master' i potem powrot do HEAD
```
git checkout a7eb01a3
git checkout master
```

### cofniecie wskaznika na stary commit i utworzenie od niego branch-a o nazwie 'new_branch'
```
git checkout 0d1d7fc32
git checkout -b new_branch
```


### cofniecie zmian do zadanego commitu na danym branchu
```
git checkout master
git reset --hard 1258f0d0aae
```

This will destroy any local modifications. Don't do it if you have uncommitted work you want to keep.
```
git reset --hard 0d1d7fc32
```
Alternatively, if there's work to keep:
```
git stash
git reset --hard 0d1d7fc32
git stash pop
```
This saves the modifications, then reapplies that patch after resetting.
You could get merge conflicts, if you've modified things which were
changed since the commit you reset to.


### usuniecie ostatniego commitu
```
git reser HEAD
```

### usuniecie kilku commitow
usuniecie 4 i 3 commitu (commmit 1 to commit pierwszy chyba)
```
git rebase --onto master~4 master~2 master  
```
Powyzej celowo jest master~2 a nie master~3 !!! . Niestety moga wystapic konflikty przy rabase takie jak przy mergowaniu. Postepowac zgodnie z instrukcjami na ekranie. Pracuje się tak jak przy mergu. Czy patrze na jakich plikach jest konflikt , potem zmieniam to recznie w plikach wedlug znacników potem daje git add <plik> i potem git rebase --continue.
W zmianach zatwierdzam to co jes ostatnie i chyba wtedy bedzie ok. 

### revert vs reset
Let's say you had commits:

C
B
A
git revert B, will create a commit that undoes changes in B.

git revert A, will create a commit that undoes changes in A, but will not touch changes in B

Note that if changes in B are dependent on changes in A, the revert of A is not possible.

git reset --soft A, will change the commit history and repository; staging and working directory will still be at state of C.

git reset --mixed A, will change the commit history, repository, and staging; working directory will still be at state of C.

git reset --hard A, will change the commit history, repository, staging and working directory; you will go back to the state of A completely.



rebase - po nim tez trzeba rozwiazywac konflikty
git diff








## merge


### zlaczenie brancha 'prod' do biezacego brancha
```
git merge prod
```

### sprawdzenie i rozwiazywanie konfliktow
Zeby zoabaczyc na jakich plikach sa konflikty (jestesmy w trakcie procesu mergowania):
```
git status
```
Nastepnie w plikach mozna zobaczyc ze beda dodane nastepujace elemenenty:

Between the <<<<<<< and =======, you will find the version as per the changes in your current branch, relative to the base commit.

Between the ======= and >>>>>>>, you will find the version according to the other branch, relative to the base commit.

For convenience, after the <<<<<<< and >>>>>>> markers, you will see hints as to which commit that part of the conflict stems from, HEAD of course being the current revision.

++<<<<<<< HEAD
++abcgh
++=======
++abcdef
++>>>>>>> prod


UStalamy jak ma wygladac wersja finalna pliku.
Nastepnie bedac dalej w procesie mergowania robimy git add . i potem git commit -m'komentarz' . Mergowania automatycznie sie zakonczy


### zaprzestanie procesu mergowania
```
git merge -abort
```























## smietnik


109

To see the difference between:

Your working copy and staging area:

% git diff
Staging area and the latest commit:

% git diff --staged
Your working copy and commit 4ac0a6733:

% git diff 4ac0a6733
Commit 4ac0a6733 and the latest commit:

% git diff 4ac0a6733 HEAD
Commit 4ac0a6733 and commit 826793951

% git diff 4ac0a6733 826793951

